# ******************* Tasks included in this Playbook *****************
# 1. Update the Repo
# 2. Install Java (openjdk-17-jre) , so that the slave can be configured.
# 3. Download Maven Packages (version 3.8.8)
# 4. Extract the downloaded Maven package to /opt
# 5. Downloading OpenJDK 17
# 6. Extract the downloaded OpenJDK 17 package to /opt
# 7. Rename the extracted openjdk directory name from jdk-17.0.2 to jdk-17
---

- hosts: jenkins-slave 
  become: true
  vars:
    user_name: maha # Define the user as a variable
  tasks:
  - name: Update Ubuntu Repository
    apt: # The apt module is used to manage packages in ubuntu
      update_cache: yes 
      cache_valid_time: 3600 # The time is in seconds after which the cache is considered as outdated.

  - name: Install java 
  # apt install openjdk-17-jre
    apt: #ansible.builtin.apt:
      name: openjdk-17-jre
      state: present 

  - name: Download Maven Packages
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
      dest: /opt 

  - name: Extract the Maven Package
    unarchive:
      src: /opt/apache-maven-3.8.8-bin.tar.gz
      dest: /opt/
      remote_src: yes  
  
  - name: Download OpenJDK 17
    get_url:
      url: https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
      dest: /opt
  
  - name: Extract Java 17 Packages 
    unarchive:
      src: /opt/openjdk-17.0.2_linux-x64_bin.tar.gz
      dest: /opt/
      remote_src: yes 

  - name: Move to Openjdk 17
    command: mv /opt/jdk-17.0.2 /opt/jdk-17
    args:
      creates: /opt/jdk-17

  - name: Create /home/{{ user_name }}/jenkins folder
    file:
      path: /home/{{ user_name }}/jenkins
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      recurse: true # Ensure Ownership is appllied recursively.
  - name: Update apt package cache
    apt:
      update_cache: yes 
    # Installing docker on Slave macine
  - name: Install Docker 
    apt:
      name: docker.io
      state: present
  - name: Add user '{{ user_name }}' to the docker group
    ansible.builtin.user: 
      name: "{{ user_name }}"
      groups: docker
      append: yes
  - name: Set Permissions on /var/run/docker.sock
    file:
      path: /var/run/docker.sock 
      mode: '0777'


# there are lot to be installed, so this will be continued.........